<div class="menu">
    <div class="menu__column">
            <h4><?php echo __('CONTACT ')?></h4>
            <ul>
                <li><a href="#"><span  class="addressicon" translate="true"><?php echo __('11-234 Lorem street, Los Angeles')?></span></a></li>
                <li><a href="#"><span  class="phoneicon" translate="true"><?php echo __('+91 8427391308')?></span></a></li>
                <li><a href="#"><span   class="emailicon" translate="true"><?php echo __('mytheme@magento.com')?></span></a></li>
            </ul>
        </div>
    <div class="menu__column">
        <h4><?php echo __('MAGENTO')?></h4>
        <ul>
            <li><a class="linkicon" href="#"><span    translate="true"><?php echo __('Customer Sevice')?></span></a></li>
            <li><a class="linkicon" href="#"><span    translate="true"><?php echo __('Faq')?></span></a></li>
            <li><a class="linkicon" href="#"><span    translate="true"><?php echo __('Shipping Information')?></span></a></li>
            <li><a class="linkicon" href="#"><span    translate="true"><?php echo __('Site terms & Conditions')?></span></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4> <?php echo __('FIND US')?></h4>
        <ul>
            <li><a href="#" ><span   class="linkicon" translate="true"><?php echo __('About Us')?></span></a></li>
            <li><a href="#" ><span   class="linkicon" translate="true"><?php echo __('Privacy Policy')?></span></a></li>
            <li><a href="#" ><span   class="linkicon" translate="true"><?php echo __('Contact Us')?></span></a></li>
        </ul>
    </div>

    <div class="footer_logo"></div>
</div>

<h4 class="divider donotcross" >Diamond Store</h4>
