	<?php if($block->getData('heading1')): ?>
	<h2 class='form'><?php echo $block->getData('heading1'); ?></h2>
	<?php endif; ?>

	<?php if($block->getData('heading1')): ?>
	<h2 class='form'><?php echo $block->getData('text_area1'); ?></h2>
	<?php endif; ?>

	<?php if($block->getData('heading1')): ?>
	<h2 class='form'><?php echo $block->getData('heading2'); ?></h2>
	<?php endif; ?>

	<?php if($block->getData('heading1')): ?>
	<h2 class='form'><?php echo $block->getData('text_area2'); ?></h2>
	<?php endif; ?>