<?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        $baseUrl=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB) . "newsletter/subscriber/new/";

?>
<div class="newslatter">
    <div class="content">
    <div class="newslattercontainer">
        <div translate="true" class="single">
            <h2>SIGN UP FOR NEWSLETTER</h2>
            <div class="input-group">
                <form class="form subscribe" action="<?=$baseUrl;?>" method="POST" id="newsletter-validate-detail">
                    <div class="control"><input id="newslatter" name="email" data-validate="{required:true, 'validate-email':true}" type="email" class="form-control" placeholder="Enter your email">
                    </div>
            <div class="actions">
            <button class="action subscribe newslatterbtn" type="submit" >SUBSCRIBE</button>
            
            </div>
            
                </form>
            </div>
        </div>
    </div>
</div>
</div>